services:
  face-recognition-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: face-recognition-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
